#!/usr/bin/env python3
"""Stage 3: extract route-relevant passages from candidate sentences.

Reads `data/generated/galen/route_candidates.json` (Stage 2 output) and
emits `data/generated/galen/passages.json` conforming to
`schemas/galen/galen-passage.schema.json`.

For each candidate sentence:
- assign a stable `passage_id` (work.book.chapter.ordinal-within-chapter)
- map each place_mention to a curator `place_key` (always — we require all
  routes places to be in `data/galen/lexicon/places.json` so the auto-detector
  emits curator slugs rather than raw Pleiades IDs)
- tag each place_mention with `evidence_category` A/B/C per the consolidated
  routes defined here (which mirror `docs/galen_route_decisions.md`)
- merge human-edited `translation_en` and `materia_mentions[]` from
  `data/galen/translations/passages.json` (a hand-authored file, not
  regenerated by this script)
- attach `route_keys[]` (the consolidated routes the candidate belongs to)
- set `is_route_anchor` per the decisions doc

Translations file format (JSON):
{
    "<passage_id>": {
        "greek": "..."  # auto-mirrored from TEI; do not edit by hand
        "translation_en": "...",
        "materia_mentions": [{"surface": "...", "materia_key": "..."}],
        "is_route_anchor": true|false,
        "notes": "free text"
    },
    ...
}

This script also writes back to `data/galen/translations/passages.json`
on every run — refreshing only the `greek` field per passage so the
curator can read Greek + English side-by-side. translation_en,
materia_mentions, is_route_anchor, and notes are preserved exactly.

Idempotent. Stable passage_ids across re-runs as long as candidate ordering
within a chapter is stable.
"""
from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CANDIDATES = ROOT / "data" / "generated" / "galen" / "route_candidates.json"
LEXICON = ROOT / "data" / "galen" / "lexicon" / "places.json"
GAZETTEER = ROOT / "data" / "generated" / "galen" / "pleiades_gazetteer.json"
TRANSLATIONS = ROOT / "data" / "galen" / "translations" / "passages.json"
OUT_PASSAGES = ROOT / "data" / "generated" / "galen" / "passages.json"


# ---------------------------------------------------------------------------
# Consolidated routes (mirror docs/galen_route_decisions.md)
# ---------------------------------------------------------------------------

ROUTES: dict[str, dict] = {
    "lemnos-alexandria-troas-to-thessalonica-context": {
        "label": "Lemnos via Alexandria Troas",
        "core_stops": ["alexandria_troas", "lemnos", "hephaistia"],
        "context": ["thessalonica", "macedonia_region", "thracia_region", "rome"],
        "do_not_map": ["samos", "chios", "aegean_sea"],
    },
    "lemnos-italy-to-troas-via-thasos": {
        "label": "Lemnos via Italy → Thasos → Troas",
        "core_stops": ["philippi", "thasos", "lemnos", "hephaistia", "alexandria_troas"],
        "context": ["italia_peninsula", "macedonia_region", "thracia_region"],
        "do_not_map": [],
    },
    "cyprus-soloi-mines": {
        "label": "Cyprus / Soloi mines",
        "core_stops": ["soloi_cyprus"],
        "context": ["cyprus_island", "asia_province", "italia_peninsula", "rome", "pergamum", "cyzicus"],
        "do_not_map": [],
    },
    "coele-syria-dead-sea-materials": {
        "label": "Coele Syria / Dead Sea materials",
        "core_stops": ["coele_syria", "dead_sea"],
        "context": ["palestine"],
        "do_not_map": ["lycia"],
    },
    "pergamum-ergasteria-mines": {
        "label": "Pergamum → Ergasteria mines",
        "core_stops": ["pergamum", "ergasteria"],
        "context": ["cyzicus", "cyprus_island"],
        "do_not_map": [],
    },
}

# Materia-medica observation layer — passages that aren't routes but contribute
# substance/place observations to the materia index.
MATERIA_LAYER_KEY = "_materia_observations"

# Map (work, kuhn_citation_start) -> list[route_key | "_materia_observations"]
# These map candidates to the routes they participate in. Format the citation
# string exactly as it appears in route_candidates.json.
CANDIDATE_ROUTES: dict[tuple[str, str], list[str]] = {
    # SMT 9.1 (two candidates with identical citations — disambiguate by ordinal)
    # First candidate (Lemnian-earth grand narrative): Cyprus + Coele Syria comparisons + the Lemnos voyage
    ("SMT", "9.1", 0): [
        "lemnos-alexandria-troas-to-thessalonica-context",
        "cyprus-soloi-mines",            # the opening Cyprus comparison contributes
        "coele-syria-dead-sea-materials" # the opening Coele Syria mention contributes
    ],
    # Second candidate (Italy → Thasos → Lemnos linear)
    ("SMT", "9.1", 1): ["lemnos-italy-to-troas-via-thasos"],
    # SMT 9.2 — Lycia + Coele Syria asphalt
    ("SMT", "9.2", 0): ["coele-syria-dead-sea-materials"],
    # SMT 9.3 candidates — all merge into cyprus-soloi-mines except the
    # Pergamum → Ergasteria one
    ("SMT", "9.3", 0): ["cyprus-soloi-mines"],          # K.XII 214.5 (Soloi acquisition)
    ("SMT", "9.3", 1): ["cyprus-soloi-mines"],          # K.XII 219.5 (ἐπεδήμησα — primary anchor)
    ("SMT", "9.3", 2): ["cyprus-soloi-mines"],          # K.XII 226.7 (mine + official + transport)
    ("SMT", "9.3", 3): ["pergamum-ergasteria-mines"],   # K.XII 229.7 (Pergamum → Ergasteria)
    ("SMT", "9.3", 4): ["cyprus-soloi-mines"],          # K.XII 238.1 (a)
    ("SMT", "9.3", 5): ["cyprus-soloi-mines"],          # K.XII 238.1 (b)
    # SMT 10.2 — REJECTED as route, kept as materia (Mysia clinical context)
    ("SMT", "10.2", 0): [MATERIA_LAYER_KEY],
    # De antidotis 1.1 — REJECTED (διῆλθον = "explained")
    ("De_antidotis", "1.1", 0): [],
    # De antidotis 1.2 — splits across multiple routes
    ("De_antidotis", "1.2", 0): [
        "cyprus-soloi-mines",
        "coele-syria-dead-sea-materials",
        "lemnos-alexandria-troas-to-thessalonica-context",
    ],
    # De antidotis 1.3 — REJECTED as route, kept as materia (Neapolis observation)
    ("De_antidotis", "1.3", 0): [MATERIA_LAYER_KEY],
    # De antidotis 1.5, 1.10, 1.14 — REJECTED entirely
    ("De_antidotis", "1.5", 0): [],
    ("De_antidotis", "1.10", 0): [],
    ("De_antidotis", "1.14", 0): [],
}

# Candidates flagged as primary anchors per the decisions doc — these get
# is_route_anchor=true. (Other accepted candidates default to false.)
PRIMARY_ANCHORS: set[tuple[str, str, int]] = {
    ("SMT", "9.1", 0),  # Lemnian-earth grand narrative
    ("SMT", "9.1", 1),  # Italy → Lemnos linear route
    ("SMT", "9.2", 0),  # Lycia + Coele Syria asphalt
    ("SMT", "9.3", 1),  # ἐπεδήμησα — strongest Cyprus presence
    ("SMT", "9.3", 2),  # at-the-mine + official + transport
    ("SMT", "9.3", 3),  # Pergamum → Ergasteria
    ("SMT", "9.3", 5),  # K.XII 238.1 (b) — εθεασαμην, strong autopsy claim
    ("De_antidotis", "1.2", 0),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify_pleiades_title(title: str) -> str:
    """Fallback place_key for Pleiades-resolved mentions not in the curator
    lexicon. lowercase + strip non-alpha. Used only to fail safely; in practice
    every route-relevant mention should be curator-resolved."""
    s = unicodedata.normalize("NFD", title)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    s = re.sub(r"[^a-zA-Z0-9]+", "_", s).strip("_").lower()
    return s or "unknown"


def kuhn_to_volume(work: str, book: str) -> str:
    if work == "SMT":
        return "XI" if int(book) <= 5 else "XII"
    if work == "De_antidotis":
        return "XIV"
    return "?"


KUHN_PAGE_RE = re.compile(r"K\.\s*([IVX]+)\s+(\d+)\.(\d+)(?:[–-](?:(\d+)\.)?(\d+))?")


def parse_kuhn(citation: str) -> tuple[str, int, int, int, int] | None:
    m = KUHN_PAGE_RE.match(citation.strip())
    if not m:
        return None
    vol = m.group(1)
    page_s = int(m.group(2))
    line_s = int(m.group(3))
    page_e = int(m.group(4)) if m.group(4) else page_s
    line_e = int(m.group(5)) if m.group(5) else line_s
    return vol, page_s, line_s, page_e, line_e


def passage_id_for(work: str, chapter_ref: str, ordinal: int) -> str:
    """Stable id: smt.9.1.a / de_antidotis.1.2.a etc."""
    work_slug = "smt" if work == "SMT" else "de_antidotis"
    suffix = chr(ord("a") + ordinal)
    return f"{work_slug}.{chapter_ref}.{suffix}"


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def load_lexicon() -> dict[str, dict]:
    """Return place_key -> entry."""
    data = json.loads(LEXICON.read_text())
    return {e["place_key"]: e for e in data}


def load_gazetteer_titles() -> dict[str, str]:
    """Return pleiades_id -> title (for fallback slugify only)."""
    g = json.loads(GAZETTEER.read_text())
    return {pid: p["title"] for pid, p in g["places"].items()}


def load_translations() -> dict[str, dict]:
    if not TRANSLATIONS.exists():
        return {}
    raw = json.loads(TRANSLATIONS.read_text())
    return raw.get("passages", raw) if isinstance(raw, dict) else {}


def sync_greek_into_translations(passages: list[dict]) -> None:
    """Mirror each passage's TEI-derived Greek into the curator translations
    file so Greek + English sit side-by-side for review. translation_en,
    materia_mentions, is_route_anchor, and notes are preserved exactly;
    only the `greek` field is rewritten."""
    if not TRANSLATIONS.exists():
        return
    raw = json.loads(TRANSLATIONS.read_text())
    src = raw.get("passages", {}) if isinstance(raw, dict) else {}
    by_id = {p["passage_id"]: p for p in passages}

    rebuilt: dict[str, dict] = {}
    # Preserve existing order; refresh `greek` for known passages.
    for pid, existing in src.items():
        if pid in by_id:
            entry: dict = {"greek": by_id[pid]["greek"]}
            for k in ("translation_en", "materia_mentions", "is_route_anchor", "notes"):
                if k in existing:
                    entry[k] = existing[k]
            rebuilt[pid] = entry
        else:
            rebuilt[pid] = existing  # leave stale entries alone
    # Append any newly-discovered passages with empty curator fields.
    for pid, p in by_id.items():
        if pid in rebuilt:
            continue
        rebuilt[pid] = {
            "greek": p["greek"],
            "translation_en": "",
            "materia_mentions": [],
            "notes": "",
        }

    raw["_authoring_notes"] = (
        "Greek surface forms preserved exactly; English follows scholarly "
        "conventions (Cyprus, Lemnos, Alexandria Troas, Coele Syria, etc.). "
        "Materia mentions cover only substances Galen describes in this "
        "specific passage; broader pharmacological context is captured at "
        "Stage 5 in materia.json. The `greek` field is auto-mirrored from "
        "the TEI by extract_passages.py — edits to it will be overwritten "
        "on the next run."
    )
    raw["passages"] = rebuilt
    TRANSLATIONS.write_text(json.dumps(raw, ensure_ascii=False, indent=2) + "\n")


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def evidence_category(place_key: str, route_keys: list[str]) -> str:
    """Compute A/B/C for a mention given the routes it participates in.

    A = place_key in `core_stops` of any of its route_keys
    B = place_key in `context` of any of its route_keys
    C = place_key in `do_not_map` of any route, OR not in any route lists
        (default for stray Pleiades resolutions).

    Materia layer: any place mentioned in a materia-only candidate is
    category B (it's the site of an observation but not a route stop).
    """
    in_route = False
    for rk in route_keys:
        if rk == MATERIA_LAYER_KEY:
            in_route = True
            continue
        r = ROUTES.get(rk)
        if not r:
            continue
        if place_key in r["core_stops"]:
            return "A"
        if place_key in r["context"]:
            return "B"
        if place_key in r["do_not_map"]:
            return "C"
        in_route = True
    return "B" if in_route else "C"


def build_passage(
    work: str,
    candidate: dict,
    ordinal_in_chapter: int,
    titles: dict[str, str],
    translation_data: dict,
) -> dict:
    chapter_ref = candidate["chapter_ref"]
    pid = passage_id_for(work, chapter_ref, ordinal_in_chapter)
    book = candidate["book"]

    # Kühn span across the candidate's sentences
    parsed = [parse_kuhn(s["kuhn_citation"]) for s in candidate["sentences"]]
    parsed = [p for p in parsed if p]
    if parsed:
        vol = parsed[0][0]
        page_start = min(p[1] for p in parsed)
        line_start = min(p[2] for p in parsed if p[1] == page_start)
        page_end = max(p[3] for p in parsed)
        line_end = max(p[4] for p in parsed if p[3] == page_end)
    else:
        vol = kuhn_to_volume(work, book)
        page_start = page_end = 0
        line_start = line_end = 0

    # Concatenated greek
    greek = " ".join(s["greek"] for s in candidate["sentences"])

    # Routes for this candidate
    route_keys = CANDIDATE_ROUTES.get((work, chapter_ref, ordinal_in_chapter), [])
    routes_for_categorization = [k for k in route_keys if k != MATERIA_LAYER_KEY]

    # Place mentions: collapse per-sentence mentions into per-passage list.
    # Prefer the explicit `place_keys` (curator-resolved slug) when the survey
    # produced it; otherwise fall back to slugifying the Pleiades title.
    seen: set[tuple[str, str]] = set()
    place_mentions: list[dict] = []
    for sent in candidate["sentences"]:
        for m in sent["place_mentions"]:
            place_keys = m.get("place_keys") or []
            ids = m.get("pleiades_ids", []) or []
            if place_keys:
                place_key = place_keys[0]
            elif ids:
                primary = ids[0]
                if primary.isdigit():
                    title = titles.get(primary, primary)
                    place_key = slugify_pleiades_title(title)
                else:
                    # Backward-compat path: an older route_candidates.json
                    # might still encode curator slugs as pleiades_ids.
                    place_key = primary
            else:
                continue
            key = (m["surface"], place_key)
            if key in seen:
                continue
            seen.add(key)
            cat = evidence_category(place_key, routes_for_categorization)
            place_mentions.append({
                "surface": m["surface"],
                "place_key": place_key,
                "evidence_category": cat,
            })

    # Materia mentions + translation come from the hand-authored translations file
    overrides = translation_data.get(pid, {})
    translation_en = overrides.get("translation_en", "")
    materia_mentions = overrides.get("materia_mentions", [])
    is_anchor_override = overrides.get("is_route_anchor")

    # is_route_anchor: explicit override wins; else use PRIMARY_ANCHORS
    if is_anchor_override is not None:
        is_anchor = bool(is_anchor_override)
    else:
        is_anchor = (work, chapter_ref, ordinal_in_chapter) in PRIMARY_ANCHORS

    return {
        "passage_id": pid,
        "work": work,
        "kuhn_volume": vol,
        "kuhn_page_start": page_start,
        "kuhn_line_start": line_start,
        "kuhn_page_end": page_end,
        "kuhn_line_end": line_end,
        "tei_div_path": f"urn:cts:greekLit:tlg0057.{'tlg075' if work == 'SMT' else 'tlg078'}.1st1K-grc1:{chapter_ref}",
        "greek": greek,
        "translation_en": translation_en,
        "route_keys": [k for k in route_keys if k != MATERIA_LAYER_KEY],
        "place_mentions": place_mentions,
        "materia_mentions": materia_mentions,
        "is_route_anchor": is_anchor,
    }


def main() -> int:
    candidates_doc = json.loads(CANDIDATES.read_text())
    lexicon = load_lexicon()
    titles = load_gazetteer_titles()
    translation_data = load_translations()

    passages: list[dict] = []

    for work, candidates in candidates_doc["candidates"].items():
        ordinal_by_chapter: dict[str, int] = {}
        for c in candidates:
            chap = c["chapter_ref"]
            ord_ = ordinal_by_chapter.get(chap, 0)
            ordinal_by_chapter[chap] = ord_ + 1
            passage = build_passage(work, c, ord_, titles, translation_data)
            passages.append(passage)

    OUT_PASSAGES.parent.mkdir(parents=True, exist_ok=True)
    OUT_PASSAGES.write_text(json.dumps(passages, ensure_ascii=False, indent=2))

    sync_greek_into_translations(passages)

    # Console summary
    print(f"Wrote {len(passages)} passages to {OUT_PASSAGES.relative_to(ROOT)}")
    by_route: dict[str, int] = {}
    anchors = 0
    untranslated = 0
    excluded = 0
    place_keys_seen: set[str] = set()
    missing_in_lexicon: set[str] = set()
    for p in passages:
        if p["is_route_anchor"]:
            anchors += 1
        if not p["translation_en"]:
            untranslated += 1
        if not p["route_keys"]:
            excluded += 1
        for rk in p["route_keys"]:
            by_route[rk] = by_route.get(rk, 0) + 1
        for m in p["place_mentions"]:
            place_keys_seen.add(m["place_key"])
            if m["place_key"] not in lexicon:
                missing_in_lexicon.add(m["place_key"])

    print(f"  primary anchors: {anchors}")
    print(f"  untranslated:    {untranslated}")
    print(f"  excluded (no route_keys): {excluded}")
    print(f"  per-route passage counts:")
    for rk, n in sorted(by_route.items()):
        print(f"    {rk}: {n}")
    print(f"  unique place_keys referenced: {len(place_keys_seen)}")
    if missing_in_lexicon:
        print(f"  place_keys NOT in lexicon (synthesized fallback):")
        for pk in sorted(missing_in_lexicon):
            print(f"    {pk}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
